import { z } from "zod"
import { command } from "./process"
import { fingerprint, publishable, redact, saveReport, type Check, type Report } from "./report"

const issueSchema = z.object({ number: z.number(), title: z.string(), body: z.string().nullable(), html_url: z.string(), state: z.string(), pull_request: z.unknown().optional() })
type Issue = z.infer<typeof issueSchema>

export interface GitHubClient {
  listIssues: (repo: string) => Promise<Issue[]>
  listComments: (repo: string, number: number) => Promise<string[]>
  createIssue: (repo: string, title: string, body: string) => Promise<Issue>
  addComment: (repo: string, number: number, body: string) => Promise<void>
}

export function matchIssue(check: Check, issues: Issue[]): Issue | undefined {
  const marker = `<!-- copo-qa:${fingerprint(check)} -->`
  return issues.find(i => !i.pull_request && i.body?.includes(marker))
}

export function issueBody(check: Check, report: Report): string {
  return redact([`<!-- copo-qa:${fingerprint(check)} -->`, `<!-- copo-qa-commit:${report.commit} -->`,
    "## Reproduced failure", "", `**${check.title}** failed twice with the same diagnostic.`, "",
    `Commit: ${report.commit}`, `Runtime: ${report.runtime}`, `Area: ${check.area}`, "Severity: needs triage", "",
    "## Reproduce", "", check.reproduction, "",
    "Expected: the check completes successfully.", "Actual: the diagnostic below occurred in both attempts.", "",
    "## Evidence", "", "~~~~text", check.attempts[0]?.evidence.slice(-7000) ?? "", "~~~~", "",
    ...check.attempts.map((a, i) => `Attempt ${i + 1}: exit ${a.exitCode}, diagnostic ${a.signature}.`), "",
    report.runUrl ? `Full logs, screenshots, and browser traces: ${report.runUrl} (QA artifact).` : "Full logs, screenshots, and browser traces are saved in the local QA report directory. The diagnostic above is included here for tracking.", "",
    "Generated by CoPo QA. Repeated failure confirms the check result; root cause and severity still need triage.", ""].join("\n"))
}

async function api(path: string, body?: object): Promise<unknown> {
  const args = ["gh", "api", path]
  if (body) args.push("--method", "POST", "--input", "-")
  const proc = Bun.spawn(args, { stdin: body ? new TextEncoder().encode(JSON.stringify(body)) : "ignore", stdout: "pipe", stderr: "pipe" })
  const [out, err, code] = await Promise.all([new Response(proc.stdout).text(), new Response(proc.stderr).text(), proc.exited])
  if (code !== 0) throw new Error(`GitHub request failed: ${redact(err).slice(-2000)}`)
  return JSON.parse(out)
}

const githubClient: GitHubClient = {
  async listIssues(repo) {
    const pages = await command(["gh", "api", "--paginate", "--slurp", `repos/${repo}/issues?state=all&per_page=100`])
    return z.array(z.array(issueSchema)).parse(JSON.parse(pages)).flat()
  },
  async listComments(repo, number) {
    const pages = await command(["gh", "api", "--paginate", "--slurp", `repos/${repo}/issues/${number}/comments?per_page=100`])
    return z.array(z.array(z.object({ body: z.string() }))).parse(JSON.parse(pages)).flat().map(c => c.body)
  },
  async createIssue(repo, title, body) {
    return issueSchema.parse(await api(`repos/${repo}/issues`, { title, body }))
  },
  async addComment(repo, number, body) {
    await api(`repos/${repo}/issues/${number}/comments`, { body })
  },
}

export async function publish(dir: string, report: Report, repo: string, limit = 3, github: GitHubClient = githubClient): Promise<void> {
  if (!/^[\w.-]+\/[\w.-]+$/.test(repo)) throw new Error("Use an explicit owner/repository for publishing")
  if (!Number.isInteger(limit) || limit < 1 || limit > 10) throw new Error("Issue limit must be 1–10")
  if (report.dirty) throw new Error("Issue publishing requires a clean reviewed checkout, so every finding points to an exact commit")
  const candidates = report.checks.filter(publishable)
  if (!candidates.length) return
  // Paginate all states so a recently closed issue is not silently duplicated.
  const issues = await github.listIssues(repo)
  let writes = 0
  for (const check of candidates) {
    const existing = matchIssue(check, issues)
    if (report.publications.some(p => p.check === check.id && ["created", "updated", "already recorded"].includes(p.action))) continue
    if (writes >= limit) {
      report.publications.push({ check: check.id, action: "deferred: per-run publication limit", url: "" })
      continue
    }
    if (existing) {
      const commitMarker = `<!-- copo-qa-commit:${report.commit} -->`
      const bodies = await github.listComments(repo, existing.number)
      if (existing.body?.includes(commitMarker) || bodies.some(body => body.includes(commitMarker))) {
        report.publications.push({ check: check.id, action: "already recorded", url: existing.html_url })
      } else {
        await github.addComment(repo, existing.number, issueBody(check, report))
        writes++
        report.publications.push({ check: check.id, action: existing.state === "closed" ? "recurrence noted on closed issue" : "updated", url: existing.html_url })
      }
    } else {
      const created = await github.createIssue(repo, `[QA] ${check.title}`, issueBody(check, report))
      issues.push(created)
      writes++
      report.publications.push({ check: check.id, action: "created", url: created.html_url })
    }
    // Preserve completed writes so a partial outage can be retried safely.
    await saveReport(dir, report)
  }
  await saveReport(dir, report)
}
